<?php
if( function_exists('register_field_group') ):

    register_field_group(array (
        'key' => 'group_554a21843e4f0',
        'title' => 'About',
        'fields' => array (
            array (
                'key' => 'field_554a21a3d8c96',
                'label' => 'Text Area 1',
                'name' => 'text_area_1',
                'prefix' => '',
                'type' => 'wysiwyg',
                'instructions' => 'This content displays to the right of the featured image',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
            ),
            array (
                'key' => 'field_554a221cd8c97',
                'label' => 'Text Area 2',
                'name' => 'text_area_2',
                'prefix' => '',
                'type' => 'wysiwyg',
                'instructions' => 'This content shows below the featured image and text area 2',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-about.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array (
            0 => 'permalink',
            1 => 'the_content',
            2 => 'excerpt',
            3 => 'custom_fields',
            4 => 'discussion',
            5 => 'comments',
            6 => 'revisions',
            7 => 'slug',
            8 => 'author',
            9 => 'format',
            10 => 'page_attributes',
            11 => 'categories',
            12 => 'tags',
            13 => 'send-trackbacks',
        ),
    ));

    register_field_group(array (
        'key' => 'group_554a34b20b6c2',
        'title' => 'Awards',
        'fields' => array (
            array (
                'key' => 'field_554a350eddfde',
                'label' => 'Textfield Top',
                'name' => 'textfield_top',
                'prefix' => '',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
            ),
            array (
                'key' => 'field_554a351bddfdf',
                'label' => 'Title Bottom',
                'name' => 'title_bottom',
                'prefix' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_554a3526ddfe0',
                'label' => 'Textarea Bottom',
                'name' => 'textarea_bottom',
                'prefix' => '',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-awards.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array (
            0 => 'the_content',
        ),
    ));

    register_field_group(array (
        'key' => 'group_5523a7fcd7063',
        'title' => 'Carousel',
        'fields' => array (
            array (
                'key' => 'field_5523a83cdade8',
                'label' => 'Carousel',
                'name' => 'slickjs_carousel',
                'prefix' => '',
                'type' => 'repeater',
                'instructions' => 'Add slides to the carrousel',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'min' => '',
                'max' => '',
                'layout' => 'table',
                'button_label' => 'Add Row',
                'sub_fields' => array (
                    array (
                        'key' => 'field_5523a882dade9',
                        'label' => 'Slide Title',
                        'name' => 'slide_title',
                        'prefix' => '',
                        'type' => 'text',
                        'instructions' => 'Add a title to this slide.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                    ),
                    array (
                        'key' => 'field_5523a8cadadea',
                        'label' => 'slide-paragraph',
                        'name' => 'slide_paragraph',
                        'prefix' => '',
                        'type' => 'text',
                        'instructions' => 'Add some paragraph text to this slide.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                    ),
                    array (
                        'key' => 'field_5523a8fadadeb',
                        'label' => 'Slide Background Image',
                        'name' => 'slide_background_image',
                        'prefix' => '',
                        'type' => 'image',
                        'instructions' => 'Add a background image to this slide',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'preview_size' => 'large',
                        'library' => 'all',
                    ),
                    array (
                        'key' => 'field_5523f8462675e',
                        'label' => 'Slide Text Color',
                        'name' => 'slide_text_color',
                        'prefix' => '',
                        'type' => 'select',
                        'instructions' => 'Select the paragraph and title text color',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array (
                            '#FFFFFF: White' => '#FFFFFF: White',
                            '#0078ae: Blue' => '#0078ae: Blue',
                            '#c3cf21: Green' => '#c3cf21: Green',
                            '#959ca1: Grey' => '#959ca1: Grey',
                            '#00bce4: Cyan' => '#00bce4: Cyan',
                            '#9c8dc3: Purple' => '#9c8dc3: Purple',
                            '#f89829: Orange' => '#f89829: Orange',
                        ),
                        'default_value' => array (
                            '' => '',
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'placeholder' => '',
                        'disabled' => 0,
                        'readonly' => 0,
                    ),
                ),
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'single-eemjii_solutions.php',
                ),
            ),
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'eemjii_services',
                ),
            ),
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-clients.php',
                ),
            ),
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-partners.php',
                ),
            ),
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-about.php',
                ),
            ),
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-awards.php',
                ),
            ),
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'eemjii_solutions',
                ),
            ),
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'default',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array (
            0 => 'the_content',
        ),
    ));

    register_field_group(array (
        'key' => 'group_554ab0d85c46e',
        'title' => 'Case Study',
        'fields' => array (
            array (
                'key' => 'field_554ab12042d75',
                'label' => 'Background',
                'name' => 'background',
                'prefix' => '',
                'type' => 'wysiwyg',
                'instructions' => 'What is the clients background?',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
            ),
            array (
                'key' => 'field_554ab17042d76',
                'label' => 'The Challenge',
                'name' => 'the_challenge',
                'prefix' => '',
                'type' => 'wysiwyg',
                'instructions' => 'What challenge did the client face?',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
            ),
            array (
                'key' => 'field_554ab18e42d77',
                'label' => 'The Solution',
                'name' => 'the_solution',
                'prefix' => '',
                'type' => 'wysiwyg',
                'instructions' => 'What solution did IP Solutions provide?',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
            ),
            array (
                'key' => 'field_554ab1a842d78',
                'label' => 'Result',
                'name' => 'result',
                'prefix' => '',
                'type' => 'wysiwyg',
                'instructions' => 'How did the solution impact the client?',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
            ),
            array (
                'key' => 'field_554b21decbceb',
                'label' => 'Footer Textbox - Title',
                'name' => 'footer_textbox_title',
                'prefix' => '',
                'type' => 'text',
                'instructions' => 'The title for the textbox located at the bottom of the case studies page',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_554b2202cbcec',
                'label' => 'Footer Textbox',
                'name' => 'footer_textbox',
                'prefix' => '',
                'type' => 'wysiwyg',
                'instructions' => 'The textbox located at the bottom of the page',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'eemjii_case_studies',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
    ));

    register_field_group(array (
        'key' => 'group_5523da55b11bf',
        'title' => 'Choose your starting point',
        'fields' => array (
            array (
                'key' => 'field_5538ccd3ab03f',
                'label' => 'Starting Point',
                'name' => 'starting_point',
                'prefix' => '',
                'type' => 'repeater',
                'instructions' => 'Add up to 4 starting points ',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'min' => '',
                'max' => 4,
                'layout' => 'table',
                'button_label' => 'Add Row',
                'sub_fields' => array (
                    array (
                        'key' => 'field_5538cf17ab040',
                        'label' => 'Starting Point Title',
                        'name' => 'starting_point_title',
                        'prefix' => '',
                        'type' => 'text',
                        'instructions' => 'Whats the title of this starting point?',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Find your...',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                    ),
                    array (
                        'key' => 'field_5538cf80ab041',
                        'label' => 'Starting Point Icon',
                        'name' => 'starting_point_icon',
                        'prefix' => '',
                        'type' => 'image',
                        'instructions' => 'Upload the Icon for this starting point',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'preview_size' => 'medium',
                        'library' => 'all',
                    ),
                    array (
                        'key' => 'field_554b36218ccb4',
                        'label' => 'Starting Point Icon - Active',
                        'name' => 'starting_point_icon_active',
                        'prefix' => '',
                        'type' => 'image',
                        'instructions' => 'Upload the Icon for this starting point',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'preview_size' => 'medium',
                        'library' => 'all',
                    ),
                    array (
                        'key' => 'field_5538cfb2ab042',
                        'label' => 'Starting Point Text',
                        'name' => 'starting_point_text',
                        'prefix' => '',
                        'type' => 'textarea',
                        'instructions' => 'Enter a brief description of this starting point',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                    ),
                    array (
                        'key' => 'field_5538cfebab043',
                        'label' => 'Starting Point URL',
                        'name' => 'starting_point_url',
                        'prefix' => '',
                        'type' => 'url',
                        'instructions' => 'Paste in where this starting point should link to',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'http://',
                    ),
                ),
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'single-eemjii_solutions.php',
                ),
            ),
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'eemjii_solutions',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array (
            0 => 'the_content',
            1 => 'featured_image',
        ),
    ));

    register_field_group(array (
        'key' => 'group_5509a4af94b19',
        'title' => 'Clients',
        'fields' => array (
            array (
                'key' => 'field_5509a8ddd92f4',
                'label' => 'Client\'s Logo',
                'name' => 'client_logo',
                'prefix' => '',
                'type' => 'image',
                'instructions' => 'Upload the clients company logo',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_5509a898d92f3',
                'label' => 'Bio',
                'name' => 'bio',
                'prefix' => '',
                'type' => 'text',
                'instructions' => 'Tell us more about this client',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'eemjii_clients',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
    ));

    register_field_group(array (
        'key' => 'group_55086dc15912d',
        'title' => 'Contact Page',
        'fields' => array (
            array (
                'key' => 'field_55086e28d9c0f',
                'label' => 'Google Map Location',
                'name' => 'google_map_location',
                'prefix' => '',
                'type' => 'google_map',
                'instructions' => 'Enter the Google Maps Co-ordinate',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'center_lat' => '',
                'center_lng' => '',
                'zoom' => '',
                'height' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-contact.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
    ));

    register_field_group(array (
        'key' => 'group_55361f9cc4e6e',
        'title' => 'Featured Image with Roll Over',
        'fields' => array (
            array (
                'key' => 'field_55361e6c3ffd6',
                'label' => 'Featured Image',
                'name' => 'featured_image',
                'prefix' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'medium',
                'library' => 'all',
            ),
            array (
                'key' => 'field_55361e963ffd7',
                'label' => 'Featured Image Rolled Over',
                'name' => 'featured_image_rolled_over',
                'prefix' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'eemjii_services',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array (
            0 => 'featured_image',
        ),
    ));

    register_field_group(array (
        'key' => 'group_55086e6b8d372',
        'title' => 'Global',
        'fields' => array (
        ),
        'location' => array (
            array (
                array (
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => '',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
    ));

    register_field_group(array (
        'key' => 'group_554108dcc61f5',
        'title' => 'Related Clients',
        'fields' => array (
            array (
                'key' => 'field_554108e91d16e',
                'label' => 'Related Client',
                'name' => 'related_client',
                'prefix' => '',
                'type' => 'relationship',
                'instructions' => 'Select the client',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array (
                    0 => 'eemjii_clients',
                ),
                'taxonomy' => '',
                'filters' => array (
                    0 => 'search',
                    1 => 'post_type',
                    2 => 'taxonomy',
                ),
                'elements' => array (
                    0 => 'featured_image',
                ),
                'max' => 1,
                'return_format' => 'object',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'eemjii_case_studies',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
    ));

    register_field_group(array (
        'key' => 'group_552baa36d00a8',
        'title' => 'Related Resources',
        'fields' => array (
            array (
                'key' => 'field_552baa4230f9b',
                'label' => 'Related Resources',
                'name' => 'related_resources',
                'prefix' => '',
                'type' => 'relationship',
                'instructions' => 'Select some related resources.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array (
                    0 => 'eemjii_resources',
                ),
                'taxonomy' => '',
                'filters' => array (
                    0 => 'search',
                    1 => 'post_type',
                    2 => 'taxonomy',
                ),
                'elements' => array (
                    0 => 'featured_image',
                ),
                'max' => '',
                'return_format' => 'object',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'eemjii_services',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
    ));

    register_field_group(array (
        'key' => 'group_552ba9eaeb650',
        'title' => 'Related Services',
        'fields' => array (
            array (
                'key' => 'field_552ba9f69ccfd',
                'label' => 'Related Services',
                'name' => 'related_services',
                'prefix' => '',
                'type' => 'relationship',
                'instructions' => 'Select some related services.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array (
                    0 => 'eemjii_services',
                ),
                'taxonomy' => '',
                'filters' => array (
                    0 => 'search',
                    1 => 'post_type',
                    2 => 'taxonomy',
                ),
                'elements' => array (
                    0 => 'featured_image',
                ),
                'max' => '',
                'return_format' => 'object',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'eemjii_resources',
                ),
            ),
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'eemjii_solutions',
                ),
            ),
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'eemjii_case_studies',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
    ));

    register_field_group(array (
        'key' => 'group_552baa63d316c',
        'title' => 'Related Solutions',
        'fields' => array (
            array (
                'key' => 'field_552baa70bb03f',
                'label' => 'Related Solutions',
                'name' => 'related_solutions',
                'prefix' => '',
                'type' => 'relationship',
                'instructions' => 'Select some related solutions.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array (
                    0 => 'eemjii_solutions',
                ),
                'taxonomy' => '',
                'filters' => array (
                    0 => 'search',
                    1 => 'post_type',
                    2 => 'taxonomy',
                ),
                'elements' => array (
                    0 => 'featured_image',
                ),
                'max' => '',
                'return_format' => 'object',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'eemjii_resources',
                ),
            ),
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'eemjii_services',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
    ));

    register_field_group(array (
        'key' => 'group_5509a2253108d',
        'title' => 'Related Testimonials',
        'fields' => array (
            array (
                'key' => 'field_55423d3209d27',
                'label' => 'Toggle Testimonial',
                'name' => 'toggled_testimonial',
                'prefix' => '',
                'type' => 'true_false',
                'instructions' => 'Check this box to add this clients testimonial',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
            ),
            array (
                'key' => 'field_5509a5c4b5e84',
                'label' => 'Author\'s name',
                'name' => 'author_name',
                'prefix' => '',
                'type' => 'text',
                'instructions' => 'Whats is the name of the testimonials author?',
                'required' => 0,
                'conditional_logic' => array (
                    array (
                        array (
                            'field' => 'field_55423d3209d27',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'Cristiano Ronaldo',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_5509a69239c96',
                'label' => 'Author\'s Job Role',
                'name' => 'authors_job_role',
                'prefix' => '',
                'type' => 'text',
                'instructions' => 'What is thier job role?',
                'required' => 0,
                'conditional_logic' => array (
                    array (
                        array (
                            'field' => 'field_55423d3209d27',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'Diver',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_5509a76339c98',
                'label' => 'Testimonial',
                'name' => 'testimonial',
                'prefix' => '',
                'type' => 'textarea',
                'instructions' => 'Enter their testimonial here - 500 characters Max',
                'required' => 0,
                'conditional_logic' => array (
                    array (
                        array (
                            'field' => 'field_55423d3209d27',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => 539,
                'rows' => 20,
                'new_lines' => 'wpautop',
                'readonly' => 0,
                'disabled' => 0,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'eemjii_clients',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
    ));

    register_field_group(array (
        'key' => 'group_55099947ddea8',
        'title' => 'Resources',
        'fields' => array (
            array (
                'key' => 'field_55099cec56727',
                'label' => 'Video',
                'name' => 'video',
                'prefix' => '',
                'type' => 'oembed',
                'instructions' => 'Paste a link to your Youtube or Vimeo video here.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'width' => '',
                'height' => '',
            ),
            array (
                'key' => 'field_55099ee0d5002',
                'label' => 'File Attachments',
                'name' => 'file_attachments',
                'prefix' => '',
                'type' => 'file',
                'instructions' => 'Upload a file to this post for your users to download.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'library' => 'uploadedTo',
                'min_size' => '',
                'max_size' => 10,
                'mime_types' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'eemjii_resources',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
    ));

    register_field_group(array (
        'key' => 'group_55086203ea483',
        'title' => 'Services',
        'fields' => array (
            array (
                'key' => 'field_5531073ec0f82',
                'label' => 'Service Content Top Title',
                'name' => 'service_content_top_title',
                'prefix' => '',
                'type' => 'text',
                'instructions' => 'Write a title for the service summary',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_553102fbc0f81',
                'label' => 'Service Content Top',
                'name' => 'service_content_top',
                'prefix' => '',
                'type' => 'wysiwyg',
                'instructions' => 'Write a brief summary of this service',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
            ),
            array (
                'key' => 'field_55086b7092526',
                'label' => 'Service Content',
                'name' => 'service_content',
                'prefix' => '',
                'type' => 'repeater',
                'instructions' => 'Enter information about this service. Each category resembles its own slide',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'min' => '',
                'max' => '',
                'layout' => 'table',
                'button_label' => 'Add Category',
                'sub_fields' => array (
                    array (
                        'key' => 'field_55086c4392527',
                        'label' => 'Section Heading',
                        'name' => 'section_heading',
                        'prefix' => '',
                        'type' => 'text',
                        'instructions' => 'Sub heading for this category',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Heading',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                    ),
                    array (
                        'key' => 'field_55086c7892528',
                        'label' => 'Section Content',
                        'name' => 'section_content',
                        'prefix' => '',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                    ),
                ),
            ),
            array (
                'key' => 'field_5531080aa238a',
                'label' => 'Service Content Bottom Title',
                'name' => 'service_content_bottom_title',
                'prefix' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_55310800a2389',
                'label' => 'Service Content Bottom',
                'name' => 'service_content_bottom',
                'prefix' => '',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'eemjii_services',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array (
            0 => 'the_content',
            1 => 'custom_fields',
        ),
    ));

    register_field_group(array (
        'key' => 'group_554b353a79332',
        'title' => 'solutions',
        'fields' => array (
            array (
                'key' => 'field_554b372a9e58c',
                'label' => 'sub-heading inside cloud',
                'name' => 'subheading_inside_cloud',
                'prefix' => '',
                'type' => 'text',
                'instructions' => 'This text appears inside a blue cloud at the top of the page',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_554b355269038',
                'label' => 'Textbox top - title',
                'name' => 'textbox_top_title',
                'prefix' => '',
                'type' => 'text',
                'instructions' => 'The title for the textbox located at the top of the solutions',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_554b369369039',
                'label' => 'Textbox top',
                'name' => 'textbox_top',
                'prefix' => '',
                'type' => 'wysiwyg',
                'instructions' => 'The textbox located at the top of the page',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
            ),
            array (
                'key' => 'field_554b36d46903a',
                'label' => 'Footer Textbox - Title',
                'name' => 'footer_textbox_title',
                'prefix' => '',
                'type' => 'text',
                'instructions' => 'The title for the textbox located at the bottom of the page',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_554b36f26903b',
                'label' => 'Footer Textbox',
                'name' => 'footer_textbox',
                'prefix' => '',
                'type' => 'wysiwyg',
                'instructions' => 'The textbox located at the bottom of the page',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
            ),
            array (
                'key' => 'field_554b377e2834b',
                'label' => 'The Solution',
                'name' => 'the_solution',
                'prefix' => '',
                'type' => 'repeater',
                'instructions' => 'Add rows of content that describe this solutions',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'min' => '',
                'max' => '',
                'layout' => 'table',
                'button_label' => 'Add Row',
                'sub_fields' => array (
                    array (
                        'key' => 'field_554b37d52834c',
                        'label' => 'Row Image',
                        'name' => 'image',
                        'prefix' => '',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                    ),
                    array (
                        'key' => 'field_554b37fa2834d',
                        'label' => 'Solution Content',
                        'name' => 'solution_content',
                        'prefix' => '',
                        'type' => 'wysiwyg',
                        'instructions' => 'Add some content for this row',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                    ),
                ),
            ),
            array (
                'key' => 'field_554b3830b4263',
                'label' => 'Contact us link',
                'name' => 'contact_us_link',
                'prefix' => '',
                'type' => 'page_link',
                'instructions' => 'Choose the contact us link',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => '',
                'taxonomy' => '',
                'allow_null' => 0,
                'multiple' => 0,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'eemjii_solutions',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
    ));

    register_field_group(array (
        'key' => 'group_55099d6c54422',
        'title' => 'Team',
        'fields' => array (
            array (
                'key' => 'field_5509a11275516',
                'label' => 'Name',
                'name' => 'name',
                'prefix' => '',
                'type' => 'text',
                'instructions' => 'What\'s their name?',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'Batman',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_5509a13693bcf',
                'label' => 'Job role',
                'name' => 'role',
                'prefix' => '',
                'type' => 'text',
                'instructions' => 'What\'s their job role within IP Solutions?',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'Superhero',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_5509a1a70be59',
                'label' => 'Department',
                'name' => 'department',
                'prefix' => '',
                'type' => 'taxonomy',
                'instructions' => 'What department are they in?',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'department',
                'field_type' => 'select',
                'allow_null' => 0,
                'load_save_terms' => 0,
                'return_format' => 'id',
                'multiple' => 0,
            ),
            array (
                'key' => 'field_5509a46da8908',
                'label' => 'Bio',
                'name' => 'short_bio',
                'prefix' => '',
                'type' => 'textarea',
                'instructions' => 'Tell us about them in 140 words',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'Enjoys eating burritos on Mondays, Tuesdays, Thursday, Fridays... and goes for a naked burrito on Wednesday...',
                'maxlength' => 140,
                'rows' => '',
                'new_lines' => 'wpautop',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_5509be581280f',
                'label' => 'Team Member Portrait',
                'name' => 'portrait',
                'prefix' => '',
                'type' => 'image',
                'instructions' => 'Upload a portrait of your team member',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'eemjii_team',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
    ));

    register_field_group(array (
        'key' => 'group_5548c8510375c',
        'title' => 'Text Area',
        'fields' => array (
            array (
                'key' => 'field_5548c85d3add7',
                'label' => 'Title',
                'name' => 'text_area_title',
                'prefix' => '',
                'type' => 'text',
                'instructions' => 'Add a title to this text area.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_5548c8a93add8',
                'label' => 'Paragraph',
                'name' => 'text_area_paragraph',
                'prefix' => '',
                'type' => 'wysiwyg',
                'instructions' => 'Write your content for this area here.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '185',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
    ));

endif;