<?php

if( function_exists('register_field_group') ):

register_field_group(array (
    'key' => 'group_5509a4af94b19',
    'title' => 'Clients',
    'fields' => array (
        array (
            'key' => 'field_5509a8ddd92f4',
            'label' => 'Client\'s Logo',
            'name' => 'client_logo',
            'prefix' => '',
            'type' => 'image',
            'instructions' => 'Upload the clients company logo',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'uploadedTo',
        ),
        array (
            'key' => 'field_5509a854d92f2',
            'label' => 'Company Name',
            'name' => 'company_name',
            'prefix' => '',
            'type' => 'text',
            'instructions' => 'What is the organisations name?',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_5509a898d92f3',
            'label' => 'Bio',
            'name' => 'bio',
            'prefix' => '',
            'type' => 'text',
            'instructions' => 'Tell us more about this client',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'eemjii_clients',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
));

register_field_group(array (
    'key' => 'group_55086dc15912d',
    'title' => 'Contact Page',
    'fields' => array (
        array (
            'key' => 'field_55086e28d9c0f',
            'label' => 'Google Map Location',
            'name' => 'google_map_location',
            'prefix' => '',
            'type' => 'google_map',
            'instructions' => 'Enter the Google Maps Co-ordinate',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'center_lat' => '',
            'center_lng' => '',
            'zoom' => '',
            'height' => '',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'page-contact.php',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
));

register_field_group(array (
    'key' => 'group_55086e6b8d372',
    'title' => 'Global',
    'fields' => array (
    ),
    'location' => array (
        array (
            array (
                'param' => 'options_page',
                'operator' => '==',
                'value' => '',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
));

register_field_group(array (
    'key' => 'group_5523da55b11bf',
    'title' => 'Home Page',
    'fields' => array (
    ),
    'location' => array (
        array (
            array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'page-home.php',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array (
        0 => 'the_content',
        1 => 'featured_image',
    ),
));

register_field_group(array (
    'key' => 'group_55099947ddea8',
    'title' => 'Resources',
    'fields' => array (
        array (
            'key' => 'field_55099cec56727',
            'label' => 'Video',
            'name' => 'video',
            'prefix' => '',
            'type' => 'oembed',
            'instructions' => 'Paste a link to your Youtube or Vimeo video here.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'width' => '',
            'height' => '',
        ),
        array (
            'key' => 'field_55099ee0d5002',
            'label' => 'File Attachments',
            'name' => 'file_attachments',
            'prefix' => '',
            'type' => 'file',
            'instructions' => 'Upload a file to this post for your users to download.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'library' => 'uploadedTo',
            'min_size' => '',
            'max_size' => 10,
            'mime_types' => '',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'eemjii_resources',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
));

register_field_group(array (
    'key' => 'group_55086203ea483',
    'title' => 'Services and Solutions',
    'fields' => array (
        array (
            'key' => 'field_55086b7092526',
            'label' => 'Service Content',
            'name' => 'service_content',
            'prefix' => '',
            'type' => 'repeater',
            'instructions' => 'Enter information about this service. Each category resembles its own slide',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'min' => '',
            'max' => '',
            'layout' => 'table',
            'button_label' => 'Add Category',
            'sub_fields' => array (
                array (
                    'key' => 'field_55086c4392527',
                    'label' => 'Section Heading',
                    'name' => 'section_heading',
                    'prefix' => '',
                    'type' => 'text',
                    'instructions' => 'Sub heading for this category',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 'Heading',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array (
                    'key' => 'field_55086c7892528',
                    'label' => 'Section Content',
                    'name' => 'section_content',
                    'prefix' => '',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                ),
            ),
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'eemjii_services',
            ),
        ),
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'eemjii_solutions',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
));

register_field_group(array (
    'key' => 'group_5523a7fcd7063',
    'title' => 'SlickJS Carousel',
    'fields' => array (
        array (
            'key' => 'field_5523a83cdade8',
            'label' => 'slickjs_carousel',
            'name' => 'slickjs_carousel',
            'prefix' => '',
            'type' => 'repeater',
            'instructions' => 'Add slides to the carrousel',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'min' => '',
            'max' => '',
            'layout' => 'table',
            'button_label' => 'Add Row',
            'sub_fields' => array (
                array (
                    'key' => 'field_5523a882dade9',
                    'label' => 'Slide Title',
                    'name' => 'slide_title',
                    'prefix' => '',
                    'type' => 'text',
                    'instructions' => 'Add a title to this slide.',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array (
                    'key' => 'field_5523a8cadadea',
                    'label' => 'slide-paragraph',
                    'name' => 'slide_paragraph',
                    'prefix' => '',
                    'type' => 'text',
                    'instructions' => 'Add some paragraph text to this slide.',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array (
                    'key' => 'field_5523a8fadadeb',
                    'label' => 'Slide Background Image',
                    'name' => 'slide_background_image',
                    'prefix' => '',
                    'type' => 'image',
                    'instructions' => 'Add a background image to this slide',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'preview_size' => 'large',
                    'library' => 'all',
                ),
            ),
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'page_template',
                'operator' => '==',
                'value' => 'page-home.php',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
));

register_field_group(array (
    'key' => 'group_55099d6c54422',
    'title' => 'Team',
    'fields' => array (
        array (
            'key' => 'field_5509a11275516',
            'label' => 'Name',
            'name' => 'name',
            'prefix' => '',
            'type' => 'text',
            'instructions' => 'What\'s their name?',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'Batman',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_5509a13693bcf',
            'label' => 'Job role',
            'name' => 'role',
            'prefix' => '',
            'type' => 'text',
            'instructions' => 'What\'s their job role within IP Solutions?',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'Superhero',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_5509a1a70be59',
            'label' => 'Department',
            'name' => 'department',
            'prefix' => '',
            'type' => 'taxonomy',
            'instructions' => 'What department are they in?',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'taxonomy' => 'department',
            'field_type' => 'select',
            'allow_null' => 0,
            'load_save_terms' => 0,
            'return_format' => 'id',
            'multiple' => 0,
        ),
        array (
            'key' => 'field_5509a46da8908',
            'label' => 'Bio',
            'name' => 'short_bio',
            'prefix' => '',
            'type' => 'textarea',
            'instructions' => 'Tell us about them in 140 words',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'Enjoys eating burritos on Mondays, Tuesdays, Thursday, Fridays... and goes for a naked burrito on Wednesday...',
            'maxlength' => 140,
            'rows' => '',
            'new_lines' => 'wpautop',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_5509be581280f',
            'label' => 'Team Member Portrait',
            'name' => 'portrait',
            'prefix' => '',
            'type' => 'image',
            'instructions' => 'Upload a portrait of your team member',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'eemjii_team',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
));

register_field_group(array (
    'key' => 'group_5509a2253108d',
    'title' => 'Testimonials',
    'fields' => array (
        array (
            'key' => 'field_5509a9f5152d3',
            'label' => 'Company Logo',
            'name' => 'company_logo',
            'prefix' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
        ),
        array (
            'key' => 'field_5509a5c4b5e84',
            'label' => 'Author\'s name',
            'name' => 'author_name',
            'prefix' => '',
            'type' => 'text',
            'instructions' => 'Whats is the name of the testimonials author?',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'Cristiano Ronaldo',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_5509a69239c96',
            'label' => 'Author\'s Job Role',
            'name' => 'authors_job_role',
            'prefix' => '',
            'type' => 'text',
            'instructions' => 'What is thier job role?',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'Diver',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_5509a70d39c97',
            'label' => 'Authors Company',
            'name' => 'authors_company',
            'prefix' => '',
            'type' => 'text',
            'instructions' => 'What company does they work for?',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        array (
            'key' => 'field_5509a76339c98',
            'label' => 'Testimonial',
            'name' => 'testimonial',
            'prefix' => '',
            'type' => 'textarea',
            'instructions' => 'Enter their testimonial here - 500 characters Max',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => 539,
            'rows' => 47,
            'new_lines' => 'wpautop',
            'readonly' => 0,
            'disabled' => 0,
        ),
    ),
    'location' => array (
        array (
            array (
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'eemjii_testimonials',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
));

endif;